// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RCMServerData.EFContext;

#nullable disable

namespace RCMServerData.Migrations
{
    [DbContext(typeof(RCMBlazorContext))]
    [Migration("20220302111651_CheckNewContext")]
    partial class CheckNewContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RCMServerData.Models.AuthorityType", b =>
                {
                    b.Property<short>("ATId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ATId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("ATId"));

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.HasKey("ATId")
                        .HasName("pk_AuthorityType_id");

                    b.ToTable("AuthorityType");
                });

            modelBuilder.Entity("RCMServerData.Models.Branch", b =>
                {
                    b.Property<short>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("BId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("BId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar")
                        .HasColumnName("Adress");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("current_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("BId")
                        .HasName("pk_Branch_id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("RCMServerData.Models.Supplier", b =>
                {
                    b.Property<int>("SpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SpId"));

                    b.Property<string>("Adress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Adress");

                    b.Property<short>("BId")
                        .HasColumnType("smallint")
                        .HasColumnName("BId");

                    b.Property<short?>("BranchBId")
                        .HasColumnType("smallint");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("CompanyName");

                    b.Property<decimal>("CurrentDept")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("CurrentDept");

                    b.Property<byte>("FTId")
                        .HasColumnType("smallint")
                        .HasColumnName("FTId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Note");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Phone");

                    b.Property<int?>("UserUId")
                        .HasColumnType("int");

                    b.HasKey("SpId");

                    b.HasIndex("BranchBId");

                    b.HasIndex("UserUId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("RCMServerData.Models.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UId"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("current_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("LastName");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Phone")
                        .IsFixedLength();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UserName");

                    b.HasKey("UId")
                        .HasName("pk_User_id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RCMServerData.Models.UserBranchAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<short>("ATId")
                        .HasColumnType("smallint")
                        .HasColumnName("ATId");

                    b.Property<short?>("AuthorityTypeATId")
                        .HasColumnType("smallint");

                    b.Property<short>("BId")
                        .HasColumnType("smallint")
                        .HasColumnName("BId");

                    b.Property<short?>("BranchBId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("UId")
                        .HasColumnType("int")
                        .HasColumnName("UId");

                    b.Property<int?>("UserUId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_UserBranchAuthority_id");

                    b.HasIndex("AuthorityTypeATId");

                    b.HasIndex("BranchBId");

                    b.HasIndex("UserUId");

                    b.ToTable("UserBranchAuthority");
                });

            modelBuilder.Entity("RCMServerData.Models.Supplier", b =>
                {
                    b.HasOne("RCMServerData.Models.Branch", "Branch")
                        .WithMany("Suppliers")
                        .HasForeignKey("BranchBId");

                    b.HasOne("RCMServerData.Models.User", "User")
                        .WithMany("Suppliers")
                        .HasForeignKey("UserUId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RCMServerData.Models.UserBranchAuthority", b =>
                {
                    b.HasOne("RCMServerData.Models.AuthorityType", "AuthorityType")
                        .WithMany("UserBranchAuthorities")
                        .HasForeignKey("AuthorityTypeATId");

                    b.HasOne("RCMServerData.Models.Branch", "Branch")
                        .WithMany("UserBranchAuthorities")
                        .HasForeignKey("BranchBId");

                    b.HasOne("RCMServerData.Models.User", "User")
                        .WithMany("UserBranchAuthorities")
                        .HasForeignKey("UserUId");

                    b.Navigation("AuthorityType");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RCMServerData.Models.AuthorityType", b =>
                {
                    b.Navigation("UserBranchAuthorities");
                });

            modelBuilder.Entity("RCMServerData.Models.Branch", b =>
                {
                    b.Navigation("Suppliers");

                    b.Navigation("UserBranchAuthorities");
                });

            modelBuilder.Entity("RCMServerData.Models.User", b =>
                {
                    b.Navigation("Suppliers");

                    b.Navigation("UserBranchAuthorities");
                });
#pragma warning restore 612, 618
        }
    }
}
